#name: Syft detection of dependencies
#on:
#  push:
#    branches:
#      - main
#      - head
#jobs:
#  syft-detection:
#    runs-on: ubuntu-latest
#    permissions:
#      actions: read
#      contents: write
#    steps:
#      - name: 'Checkout Repository'
#        uses: actions/checkout@v5
#      - uses: anchore/sbom-action@8e94d75ddd33f69f691467e42275782e4bfefe84 # v0.20.9
#        with:
#          path: .
#          dependency-snapshot: true
